version: 2.1
jobs: 
  install:
    docker:
      - image: circleci/node:dubnium-browsers
    steps: 
      - checkout
      - restore_cache: 
          keys: 
            - yarn-packages-{{ checksum "yarn.lock" }}-{{ .Environment.CACHE_VERSION }}
            - yarn-packages
      - run: yarn global add node-gyp && yarn install
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}-{{ .Environment.CACHE_VERSION }}
          paths: 
            - node_modules

workflows:
  build_deploy: 
    jobs: 
      - install